### ISSUE TITLE
First page builder field will not show columns on Posts

### ISSUE THREAD

**Issue by egg-beater-tyler** [Angrycreative/ACF-Page-Builder-Field#4]
Single page builder fields will not show columns however following page builder fields will. If there is an active page builder in the standard wordpress editor area with columns, the first page builder field WILL show rows.

**Comment by pelmered** [comment]
Thank you for reporting @egg-beater-tyler! 

This is a know issue/limitation. It is a somewhat complex issue, and we are not sure how to tackle this or if it's something that needs fixing. 

As it says in the bullet for this under [Known issues and limitations](https://github.com/Angrycreative/ACF-Page-Builder-Field#known-issues-and-limitations) there are workarounds for this. Here you find this: 

> "We recommend using ACF Page Builder fields instead and removing the normal post content completely on ACF-pages in WP-Admin."

Would this solve your problem? 
If not, please motivate you need this fix and we will consider prioritising this.

**Comment by egg-beater-tyler** [comment]
Thanks for your response @pelmered 

Unfortunately we have removed the Wordpress post content from our template and have also removed the Wordpress Wysiwig editor from the admin area with a function and neither/nor is working. 

We are also finding that if we want to have a layout with for example a 2 column row, a 4 column row and a 1 column row in the acf page buiilder field we need to replicate that layout in the standard content area so that it will work properly in the page builder field. I hope that helps. Please let me know if you need more details or debugging info.

**Comment by pelmered** [comment]
I'm sorry that you are having problems with the plugin. Unfortunately, I'm not sure I understand what you mean. I you don't mind, it would be great if you could give me another more detailed description of how you are using the page builder field and describe what the problem is. Maybe you could add some screenshots or links that shows your configuration, what you are trying to build and the problem(if applicable).
If you don't want to post anything like that publicly, you can send an e-mail to me at: peter.elmered@angrycreative.se
